stages:
  - build

job:
  tags:
    - basic
  stage: build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
    - git branch
    - pwd
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days